State:6
Info:正式版 1.20.1, Forge 47.4.16, Authlib 验证
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Anvil.png
ReleaseTime:2023-06-12 21:25
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:47.4.16
VersionNeoForge:
VersionApiCode:47040016
VersionOriginal:1.20.1
VersionOriginalMain:20
VersionOriginalSub:1
VersionArgumentIndieV2:True
VersionServerAuthServer:https://littleskin.cn/api/yggdrasil
VersionServerLogin:4
VersionServerAuthRegister:https://littleskin.cn/auth/register
VersionServerAuthName:LittleSkin 登录
VersionVanillaName:1.20.1
VersionVanilla:20.0.1
